'use client';

import { useClientArtifact } from '../../app/home/(user)/mypraxis/_lib/hooks/use-client-artifacts';
import { Loader2, Copy, Check } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { Button } from '@kit/ui/button';
import { useState, useRef } from 'react';

interface ClientBioProps {
  clientId: string;
  clientName: string;
}

export function ClientBio({ clientId, clientName }: ClientBioProps) {
  // Fetch the bio for the client
  const { 
    data: bioData, 
    isLoading: isLoadingBio,
    error
  } = useClientArtifact(clientId, 'client_bio', !!clientId);
  
  // Copy functionality
  const [isCopied, setIsCopied] = useState(false);
  const copyTimeout = useRef<NodeJS.Timeout | undefined>(undefined);
  
  const handleCopyText = (text: string | undefined) => {
    if (!text) return;
    
    navigator.clipboard.writeText(text);
    setIsCopied(true);
    
    if (copyTimeout.current) {
      clearTimeout(copyTimeout.current);
    }
    
    copyTimeout.current = setTimeout(() => {
      setIsCopied(false);
    }, 2000);
  };

  return (
    <div className="w-full px-6 pt-6 border-r border-[#E5E7EB] bg-white">
      <h2 className="text-[24px] font-semibold text-[#111827] tracking-[-0.011em] truncate">
        Client Bio - {clientName}
      </h2>
      
      {isLoadingBio ? (
        <div className="mt-5 flex items-center justify-center min-h-[200px]" data-test="client-bio-loading">
          <div className="flex flex-col items-center gap-2">
            <Loader2 className="h-6 w-6 animate-spin text-primary" />
            <p className="text-sm text-muted-foreground">Loading client bio...</p>
          </div>
        </div>
      ) : error ? (
        <div className="mt-5 rounded-lg bg-destructive/10 p-6 text-destructive" data-test="client-bio-error">
          <p className="font-medium">Error loading client bio</p>
          <p className="text-sm mt-1">Please try again later</p>
        </div>
      ) : !bioData ? (
        <div className="mt-5 rounded-lg bg-[#FFF9E8] p-6" data-test="client-bio-empty">
          <p className="text-[#374151] text-[14px] leading-[1.6]">
            Not available yet. Will be generated by AI once sufficient information is gathered.
          </p>
        </div>
      ) : (
        <div className="mt-5 rounded-lg bg-[#FFF9E8] p-6 relative group" data-test="client-bio-content">
          <Button
            variant="ghost"
            size="icon"
            className="h-6 w-6 hover:bg-transparent absolute top-3 right-3 opacity-0 group-hover:opacity-100 transition-opacity"
            onClick={() => handleCopyText(bioData.content)}
            data-test="copy-bio-button"
          >
            {isCopied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
          </Button>
          <div className="markdown-content text-[#374151] text-[14px] leading-[1.6]">
            <ReactMarkdown>{bioData.content}</ReactMarkdown>
          </div>
        </div>
      )}
    </div>
  )
}
