interface ClientBioProps {
  clientName: string
  isNewClient?: boolean // Keeping for backward compatibility
}

export function ClientBio({ clientName }: ClientBioProps) {
  // For now, we'll only have Mike's bio
  const hasBioData = clientName === "Mike"

  if (!hasBioData) {
    return (
      <div className="w-full px-6 pt-6 border-r border-[#E5E7EB] bg-white">
        <h2 className="text-[24px] font-semibold text-[#111827] tracking-[-0.011em] truncate">
          Client Bio - {clientName}
        </h2>
        <div className="mt-5 rounded-lg bg-[#FFF9E8] p-6">
          <p className="text-[#374151] text-[14px] leading-[1.6]">
            Not available yet. Will be generated by AI once sufficient information is gathered.
          </p>
        </div>
      </div>
    )
  }

  // If we reach here, we have bio data (currently only for Mike)
  return (
    <div className="w-full px-6 pt-6 border-r border-[#E5E7EB] bg-white">
      <h2 className="text-[24px] font-semibold text-[#111827] tracking-[-0.011em] truncate">
        Client Bio - {clientName}
      </h2>
      <div className="mt-5 rounded-lg bg-[#FFF9E8] p-6">
        <div className="space-y-4 text-[#374151] text-[14px] leading-[1.6]">
          <p>
            Mike Miller is a 39-year-old marketing executive who initially sought therapy for work-related stress and
            anxiety. He has been experiencing increasing pressure at work, coupled with difficulties balancing his
            professional responsibilities and family life.
          </p>
          <p>
            In our sessions, Mike has revealed patterns of perfectionism and people-pleasing tendencies that stem from
            his childhood experiences. As the second oldest of four children, he often felt responsible for maintaining
            harmony in the family and supporting his parents during financially challenging times.
          </p>
          <p>
            His grandmother&apos;s death when he was in college was a significant loss, as she had been his primary emotional
            support. This event coincided with a period of academic struggle, reinforcing his belief that he needs to be
            self-reliant and avoid &quot;burdening&quot; others with his problems.
          </p>
          <p>
            Mike&apos;s relationship with his wife Sarah is generally supportive, though he admits to withholding his feelings
            to &quot;protect&quot; her from his stress. He is deeply committed to being present for his two children (ages 8 and
            5), which adds to his anxiety about work performance and financial stability.
          </p>
          <p>
            Recent progress includes Mike&apos;s willingness to delegate more at work and communicate his needs more openly
            with his wife. He has begun practicing mindfulness techniques to manage his anxiety and is showing increased
            self-awareness about his perfectionist tendencies.
          </p>
        </div>
      </div>
    </div>
  )
}
