interface ClientOverviewProps {
  clientId: string
  isNewClient?: boolean // Keeping for backward compatibility
}

const CLIENT_OVERVIEWS: Record<string, string[]> = {}

export function ClientOverview({ clientId }: ClientOverviewProps) {
  const overview = CLIENT_OVERVIEWS[clientId]

  if (!overview) {
    return (
      <div className="w-full px-6 pt-6 bg-white">
        <h2 className="text-[24px] font-semibold text-[#111827] tracking-[-0.011em] truncate">Conceptualization</h2>
        <div className="mt-5 rounded-lg bg-[#FFF9E8] p-6">
          <p className="text-[#374151] text-[14px] leading-[1.6]">
            Not available yet. Will be generated by AI once sufficient information is gathered.
          </p>
        </div>
      </div>
    )
  }

  return (
    <div className="w-full px-6 pt-6 bg-white">
      <h2 className="text-[24px] font-semibold text-[#111827] tracking-[-0.011em] truncate">Conceptualization</h2>

      <div className="mt-5 rounded-lg bg-[#FFF9E8] p-6">
        <div className="text-[#374151] text-[14px] leading-[1.6]">
          {overview.map((paragraph, index) => (
            <p key={index} className={index > 0 ? "mt-4" : undefined}>
              {paragraph}
            </p>
          ))}
        </div>
      </div>
    </div>
  )
}
