'use client';

import { useClientArtifact } from '../../app/home/(user)/mypraxis/_lib/hooks/use-client-artifacts';
import { Loader2, Copy, Check, RefreshCw } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { Button } from '@kit/ui/button';
import { Badge } from '@kit/ui/badge';
import { useState, useRef, useEffect } from 'react';
import { useQueryClient } from '@tanstack/react-query';

interface ClientPrepNoteProps {
  clientId: string;
}

export function ClientPrepNote({ clientId }: ClientPrepNoteProps) {
  const queryClient = useQueryClient();
  const mountCountRef = useRef(0);
  const renderCountRef = useRef(0);
  
  // THEORY 1: Component Remounting - Log when component mounts/renders
  useEffect(() => {
    mountCountRef.current += 1;
    console.log(`[ClientPrepNote] MOUNTED (count: ${mountCountRef.current}) for client: ${clientId}`);
    
    return () => {
      console.log(`[ClientPrepNote] UNMOUNTED for client: ${clientId}`);
    };
  }, [clientId]);
  
  // Fetch the prep note for the client
  const { 
    data: prepNoteData, 
    isLoading: isLoadingPrepNote,
    isFetching,
    error,
    refetch: _refetch // Renamed to indicate it's unused
  } = useClientArtifact(clientId, 'client_prep_note', !!clientId);
  
  // THEORY 2: Loading State Management - Log React Query state
  useEffect(() => {
    renderCountRef.current += 1;
    console.log(`[ClientPrepNote] RENDER #${renderCountRef.current} for client: ${clientId}`);
    console.log(`[ClientPrepNote] QUERY STATE:`, { 
      hasData: !!prepNoteData, 
      isLoading: isLoadingPrepNote, 
      isFetching
    });
  });
  
  // THEORY 3: Cache Structure Mismatch - Check if cache is being hit
  useEffect(() => {
    const queryKey = ['client', clientId, 'artifact', 'client_prep_note'];
    const cachedData = queryClient.getQueryData(queryKey);
    console.log(`[ClientPrepNote] CACHE CHECK for ${queryKey.join(':')}:`, { 
      cacheHit: !!cachedData
    });
  }, [clientId, queryClient]);
  
  // We no longer need to force refetch as we're using prefetching
  // This commented code is kept for reference
  /*
  useEffect(() => {
    // Force refetch when component mounts
    refetch();
    
    // Also refetch when component becomes visible
    const handleVisibilityChange = () => {
      if (document.visibilityState === 'visible') {
        // Reset cache and force refetch
        queryClient.resetQueries({ queryKey: ['client', clientId, 'artifact', 'client_prep_note'] });
        refetch();
      }
    };
    
    document.addEventListener('visibilitychange', handleVisibilityChange);
    
    return () => {
      document.removeEventListener('visibilitychange', handleVisibilityChange);
    };
  }, [clientId, refetch, queryClient]);
  */
  
  // Track if the prep note is stale (being updated)
  const [isPrepNoteStale, setIsPrepNoteStale] = useState(false);
  
  // Update stale state when data changes
  useEffect(() => {
    if (prepNoteData) {
      setIsPrepNoteStale(prepNoteData.stale);
    }
  }, [prepNoteData]);
  
  // Copy functionality
  const [isCopied, setIsCopied] = useState(false);
  const copyTimeout = useRef<NodeJS.Timeout | undefined>(undefined);
  
  const handleCopyText = (text: string | undefined) => {
    if (!text) return;
    
    navigator.clipboard.writeText(text);
    setIsCopied(true);
    
    if (copyTimeout.current) {
      clearTimeout(copyTimeout.current);
    }
    
    copyTimeout.current = setTimeout(() => {
      setIsCopied(false);
    }, 2000);
  };

  return (
    <div className="w-full px-6 pt-6 bg-white">
      <h2 className="text-[24px] font-semibold text-[#111827] tracking-[-0.011em]">
        Preparation Note
      </h2>
      
      {isLoadingPrepNote ? (
        <div className="mt-5 flex items-center justify-center min-h-[200px]" data-test="client-prep-note-loading">
          <div className="flex flex-col items-center gap-2">
            <Loader2 className="h-6 w-6 animate-spin text-primary" />
            <p className="text-sm text-muted-foreground">Loading preparation note...</p>
          </div>
        </div>
      ) : error ? (
        <div className="mt-5 rounded-lg bg-destructive/10 p-6 text-destructive" data-test="client-prep-note-error">
          <p className="font-medium">Error loading preparation note</p>
          <p className="text-sm mt-1">Please try again later</p>
        </div>
      ) : !prepNoteData ? (
        <div className="mt-5 rounded-lg bg-[#FFF9E8] p-6" data-test="client-prep-note-empty">
          <p className="text-[#374151] text-[14px] leading-[1.6]">
            Not available yet. Will be generated by AI once sufficient information is gathered.
          </p>
        </div>
      ) : (
        <div className="mt-5 rounded-lg bg-[#FFF9E8] p-6 relative group" data-test="client-prep-note-content">
          {isPrepNoteStale && (
            <div className="absolute right-2 top-2">
              <Badge variant="outline" className="flex items-center gap-1 bg-white">
                <RefreshCw className="h-3 w-3 animate-spin" />
                <span>Updating</span>
              </Badge>
            </div>
          )}
          <Button
            variant="ghost"
            size="icon"
            className="h-6 w-6 hover:bg-transparent absolute right-3 opacity-0 group-hover:opacity-100 transition-opacity"
            style={{ top: isPrepNoteStale ? '40px' : '3px' }}
            onClick={() => handleCopyText(prepNoteData.content)}
            data-test="copy-prep-note-button"
          >
            {isCopied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
          </Button>
          <div className="markdown-content text-[#374151] text-[14px] leading-[1.6]">
            <ReactMarkdown>{prepNoteData.content}</ReactMarkdown>
          </div>
        </div>
      )}
    </div>
  )
}
