import { type DemoClientId, type ClientId, prepNotes } from "../../data/mypraxis/prep-notes"

interface PrepNoteProps {
  clientId: ClientId
  isNewClient?: boolean // Keeping for backward compatibility
}

export function PrepNote({ clientId }: PrepNoteProps) {
  // Check if this is a demo client with predefined notes
  const isDemoClient = (id: string): id is DemoClientId => {
    return Object.keys(prepNotes).includes(id)
  }
  
  const note = isDemoClient(clientId) ? prepNotes[clientId] : null

  if (!note) {
    return (
      <div className="w-full px-6 pt-6 border-r border-[#E5E7EB] bg-white">
        <h2 className="text-[24px] font-semibold text-[#111827] tracking-[-0.011em]">Prep Note</h2>
        <div className="mt-5 rounded-lg bg-[#FFF9E8] p-6">
          <p className="text-[#374151] text-[14px] leading-[1.6]">
            Not available yet. Will be generated by AI once sufficient information is gathered.
          </p>
        </div>
      </div>
    )
  }

  return (
    <div className="w-full px-6 pt-6 border-r border-[#E5E7EB] bg-white">
      <h2 className="text-[24px] font-semibold text-[#111827] tracking-[-0.011em] truncate">{note.title}</h2>

      <div className="mt-5 rounded-lg bg-[#FFF9E8] p-6">
        <div className="space-y-4 text-[#374151] text-[14px] leading-[1.6]">
          {note.content.map((paragraph, index) => (
            <p key={index}>{paragraph}</p>
          ))}
        </div>
      </div>
    </div>
  )
}
