// No imports needed

interface PrepNoteProps {
  clientId: string
  title?: string
  content?: string[]
  isNewClient?: boolean // Keeping for backward compatibility
}

export function PrepNote({ clientId, title, content }: PrepNoteProps) {
  // If no content is provided, show placeholder
  if (!content || content.length === 0) {
    return (
      <div className="w-full px-6 pt-6 bg-white">
        <h2 className="text-[24px] font-semibold text-[#111827] tracking-[-0.011em]">Prep Note</h2>
        <div className="mt-5 rounded-lg bg-[#FFF9E8] p-6">
          <p className="text-[#374151] text-[14px] leading-[1.6]">
            Not available yet. Will be generated by AI once sufficient information is gathered.
          </p>
        </div>
      </div>
    )
  }

  return (
    <div className="w-full px-6 pt-6 bg-white">
      <h2 className="text-[24px] font-semibold text-[#111827] tracking-[-0.011em] truncate">{title || "Prep Note"}</h2>

      <div className="mt-5 rounded-lg bg-[#FFF9E8] p-6">
        <div className="space-y-4 text-[#374151] text-[14px] leading-[1.6]">
          {content.map((paragraph, index) => (
            <p key={index}>{paragraph}</p>
          ))}
        </div>
      </div>
    </div>
  )
}
