'use strict';

/**
 * Shared mock responses for AI providers
 * This file provides consistent mock responses that can be used by different AI client mocks
 */

// Function to get mock responses with provider name injected
export function getMockResponses(providerName: string, modelName: string): Record<string, string> {
  return {
    // Session therapist summary response
    'session_therapist_summary': `
# Session Summary (Generated by ${providerName} ${modelName})

## Presenting Issues
- Work-related anxiety, particularly during meetings and presentations
- Physical symptoms: racing heart, sweating, breathing difficulties
- Worsening over the past few months since getting a new manager

## Client Insights
- Client recognizes avoidance is not a sustainable coping strategy
- Shows awareness of the connection between anxiety and workplace pressure
- Demonstrates willingness to address the issue

## Therapeutic Focus
- Anxiety management techniques
- Gradual exposure to anxiety-provoking situations
- Exploring the relationship between perfectionism and anxiety

## Next Steps
- Introduce breathing and grounding techniques
- Develop a hierarchy for gradual exposure
- Explore cognitive restructuring for anxious thoughts
`,

    // Client summary response
    'session_client_summary': `
# Session Highlights (Generated by ${providerName} ${modelName})

We discussed your anxiety at work, especially during presentations and meetings. You mentioned physical symptoms like a racing heart and difficulty breathing, which started after your new manager arrived.

## What We Learned
- Your anxiety is triggered by high-pressure situations at work
- You've been avoiding these situations when possible
- You recognize this isn't a long-term solution

## For Next Time
- We'll work on some breathing techniques to help manage anxiety in the moment
- We'll create a plan to gradually face anxiety-provoking situations
- We'll explore how your thoughts might be contributing to your anxiety

Remember that experiencing anxiety is common, and there are effective strategies to manage it. I'm looking forward to our next session where we'll start working on these tools.
`,

    // Client preparation note response
    'client_prep_note': `
# Preparation Note for Next Session (Generated by ${providerName} ${modelName})

## Follow-up Points from Previous Session
- Check progress with breathing exercises for anxiety management
- Review any situations where client attempted to face anxiety-provoking scenarios
- Explore any insights about thought patterns contributing to anxiety

## Client Context to Remember
- Recently got a new manager who has high expectations
- Experiencing physical symptoms during meetings and presentations
- Using avoidance as primary coping mechanism

## Therapeutic Approaches to Consider
- Continue with Gestalt approach focusing on present awareness
- Introduce cognitive restructuring techniques for anxious thoughts
- Consider gradual exposure hierarchy development

## Exploration Questions
- "How have the breathing techniques worked for you in anxious moments?"
- "What thoughts come up right before you feel anxious in meetings?"
- "What would feel like a small, manageable step toward facing a work presentation?"
`,

    // Client conceptualization response
    'client_conceptualization': `
# Client Conceptualization (Generated by ${providerName} ${modelName})

## Presenting Concerns
Client presents with work-related anxiety that manifests primarily in meeting and presentation contexts. Physical symptoms include racing heart, sweating, and breathing difficulties. These symptoms have intensified following the arrival of a new manager approximately three months ago. Client reports using avoidance as a primary coping strategy while recognizing its limitations as a long-term solution.

## Relevant History
Client reports no previous formal mental health diagnosis but describes being "high-strung" throughout academic and professional career. Achieved significant academic and career success through perfectionism and extensive preparation, which has become more difficult to maintain under new management style. Family history includes a father described as having "high standards" and a mother who was "supportive but anxious."

The anxiety appears to represent unfinished business related to authority figures and performance expectations, possibly connected to earlier life experiences that haven't been fully integrated. The physical symptoms represent the embodiment of this unfinished business, manifesting as disruptions in the client's ability to be fully present in professional situations.

## Current Life Situation
Lives with spouse who is described as supportive but sometimes frustrated by client's increasing work stress. No children. Reports a small but consistent social network, though has been withdrawing from social activities due to work stress. Physical health is generally good with regular exercise routine that has become less consistent in recent months.

## Strengths and Resources
- Strong analytical abilities and problem-solving skills
- History of professional success and advancement
- Supportive marriage and stable home environment
- Good insight into patterns and willingness to change
- Financial stability allowing for focus on therapeutic work

## Treatment Goals (Client's Perspective)
- Reduce anxiety symptoms in workplace settings
- Develop coping strategies for high-pressure situations
- Improve work-life balance
- Return to previous level of workplace confidence and performance
`,

    // Client bio response
    'client_bio': `
# Client Biography (Generated by ${providerName} ${modelName})

## Personal Information
Name: [Client Name]
Age: 34
Occupation: Marketing Manager
Relationship Status: Married, 5 years

## Presenting Issues
- Work-related anxiety, particularly in meetings and presentations
- Avoidance of high-pressure situations at work
- Physical symptoms: racing heart, sweating, difficulty breathing
- Onset: 3 months ago, coinciding with new manager starting

## Relevant History
- No prior history of anxiety disorders
- Previously thrived in collaborative work environments
- No current medications
- No substance use concerns
- Regular exercise routine (recently less consistent)

## Strengths and Resources
- Strong analytical abilities and problem-solving skills
- History of professional success and advancement
- Supportive marriage and stable home environment
- Good insight into patterns and willingness to change
- Financial stability allowing for focus on therapeutic work

## Treatment Goals (Client's Perspective)
- Reduce anxiety symptoms in workplace settings
- Develop coping strategies for high-pressure situations
- Improve work-life balance
- Return to previous level of workplace confidence and performance
`,

    // Session title generation mock
    'session_title': `Workplace Anxiety Management (${providerName} ${modelName})`,
  };
}

/**
 * Determine which mock response to return based on the prompt content
 */
export function getMockResponseForPrompt(prompt: string, mockResponses: Record<string, string>): string {
  const defaultResponse = 'Mock response for testing purposes.';
  let response = defaultResponse;
  
  if (prompt.includes('session_therapist_summary') && mockResponses.session_therapist_summary) {
    response = mockResponses.session_therapist_summary;
  } else if (prompt.includes('session_client_summary') && mockResponses.session_client_summary) {
    response = mockResponses.session_client_summary;
  } else if (prompt.includes('client_prep_note') && mockResponses.client_prep_note) {
    response = mockResponses.client_prep_note;
  } else if (prompt.includes('client_conceptualization') && mockResponses.client_conceptualization) {
    response = mockResponses.client_conceptualization;  
  } else if (prompt.includes('client_bio') && mockResponses.client_bio) {
    response = mockResponses.client_bio;
  } else if (prompt.includes('session_title') && mockResponses.session_title) {
    response = mockResponses.session_title;
  }
  
  return response;
}
